one installer with the template name as parameter

diff --git a/installer/ej b/installer/ej
--- a/installer/ej
+++ b/installer/ej
@@ -1,9 +1,18 @@
 #!/bin/bash
 
 # -----------------------------------------------------------------------------
-# EJ-BASE
+# EJ INSTALLER
 # -----------------------------------------------------------------------------
-export INSTALLER="ej-base"
+# The first argument is the template name and we need it.
+if [ -z "$1" ]
+then
+	echo "ERROR: missing argument. The template name is required"
+	echo "usage:"
+	echo "         bash ej <TEMPLATE_NAME>"
+	exit 1
+fi
+
+export INSTALLER="$1"
 export CONFIG_FILE="${INSTALLER}.conf"
 export FREE_SPACE_NEEDED="1000000"
 
